In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, SimpleRNN, GRU, LSTM, Bidirectional, Embedding

<h1>Natural Language Processing</h1>

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
# Input - batch size, time, variables
# Works as many to one
rnn = Sequential([
    Input(shape = (10, 4)), 
    SimpleRNN(64, activation = "relu")
])

In [5]:
rnn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 64)                4416      
Total params: 4,416
Trainable params: 4,416
Non-trainable params: 0
_________________________________________________________________


In [6]:
# Many to one - middle layers get all the states with return_sequences = True
rnn2 = Sequential([
    Input((10, 4)),
    SimpleRNN(64, activation = "relu", return_sequences = True),
    SimpleRNN(32, activation = "relu", return_sequences = True),
    SimpleRNN(16, activation = "relu", return_sequences = True),
    SimpleRNN(8, activation = "relu", return_sequences = True)
])

In [7]:
rnn2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 10, 64)            4416      
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 10, 32)            3104      
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 10, 16)            784       
_________________________________________________________________
simple_rnn_4 (SimpleRNN)     (None, 10, 8)             200       
Total params: 8,504
Trainable params: 8,504
Non-trainable params: 0
_________________________________________________________________


In [8]:
x = np.random.normal(size = (53, 10, 4))

In [9]:
rnn2.predict(x).shape

(53, 10, 8)

In [10]:
rnn2.predict(x)[:, -1, :]

array([[0.75195587, 0.16047144, 0.38934693, 0.        , 0.        ,
        0.        , 0.        , 0.4603609 ],
       [0.7803745 , 0.        , 0.29614043, 0.        , 0.6213677 ,
        0.        , 0.        , 0.        ],
       [1.1326914 , 0.10194144, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.51554275],
       [1.043981  , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.38945132],
       [0.4238873 , 0.13154411, 1.1313295 , 0.        , 0.        ,
        0.        , 0.        , 0.6740159 ],
       [1.0202465 , 0.28048122, 0.4132828 , 0.        , 0.6236322 ,
        0.        , 0.        , 0.3638309 ],
       [1.1789829 , 0.22481132, 0.1877478 , 0.        , 0.        ,
        0.        , 0.        , 0.36679906],
       [1.0019667 , 0.        , 0.4741251 , 0.        , 0.        ,
        0.        , 0.        , 0.45598713],
       [1.2202262 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.      

In [11]:
rnn3 = Model()
iput_layer = Input((10, 4))
rnn3_layer1 = SimpleRNN(64, return_sequences = True, return_state = True)

In [12]:
data = np.random.normal(size = (16, 10, 4))

In [13]:
rnn3_layer1(data)

[<tf.Tensor: shape=(16, 10, 64), dtype=float32, numpy=
 array([[[ 3.78688902e-01, -2.88910568e-01, -1.13231055e-01, ...,
          -2.90786296e-01, -1.05120048e-01,  2.68127915e-04],
         [ 2.89989024e-01,  7.86519796e-02,  5.98941982e-01, ...,
          -2.50282258e-01, -3.11967045e-01,  2.09790900e-01],
         [ 2.10488886e-01, -4.70074832e-01, -5.91337420e-02, ...,
          -3.01645488e-01, -2.62623765e-02,  3.30594599e-01],
         ...,
         [-9.30615067e-01, -9.13337171e-01, -5.22199452e-01, ...,
          -2.88423389e-01,  2.64042079e-01,  8.47934037e-02],
         [-7.55558491e-01,  8.79485607e-01, -4.06990260e-01, ...,
          -3.71129274e-01, -1.79317266e-01,  7.78075874e-01],
         [-6.81250513e-01, -2.41353422e-01, -5.07072985e-01, ...,
          -1.07420040e-02, -4.14928317e-01,  7.74971783e-01]],
 
        [[-6.03223324e-01,  2.12731674e-01, -5.26835024e-01, ...,
          -1.04914285e-01,  3.26183349e-01,  2.56327629e-01],
         [-9.46120024e-02,  1.51

In [14]:
# Provides the opinion of each of the neurons
gru = GRU(64, return_sequences = True, return_state = True)

In [15]:
gru(x)

[<tf.Tensor: shape=(53, 10, 64), dtype=float32, numpy=
 array([[[-0.11120722,  0.13113876, -0.12999654, ..., -0.08596004,
           0.04196836,  0.11731999],
         [ 0.05899559, -0.04865288,  0.09470175, ..., -0.02296623,
           0.00052813, -0.01451921],
         [ 0.01889223,  0.0191672 , -0.03405681, ...,  0.18405576,
          -0.01507587, -0.10468798],
         ...,
         [ 0.10354898, -0.06258602,  0.05459619, ...,  0.04614729,
          -0.03385657, -0.06381813],
         [ 0.11064478,  0.11063097, -0.0593687 , ...,  0.05203646,
           0.05678774, -0.14618039],
         [ 0.22904085,  0.23950744,  0.00518782, ..., -0.06875141,
           0.13323563, -0.07625547]],
 
        [[-0.07506537,  0.01579155, -0.06304785, ..., -0.0464885 ,
           0.00941453,  0.03645188],
         [-0.07420113, -0.02449427, -0.09817435, ...,  0.19046582,
          -0.08359881, -0.10831448],
         [-0.16293359, -0.18006116,  0.00684814, ...,  0.10490522,
          -0.1423213 ,  0.023

In [16]:
lstm = LSTM(64, return_sequences = True, return_state = True)

In [17]:
lstm(x)

[<tf.Tensor: shape=(53, 10, 64), dtype=float32, numpy=
 array([[[-0.0614888 ,  0.01021509,  0.04323178, ..., -0.10250508,
          -0.0748551 ,  0.03152332],
         [ 0.0059546 , -0.01978521, -0.00954752, ..., -0.02257898,
          -0.01354256,  0.00766207],
         [ 0.02451482,  0.02377934, -0.00872909, ...,  0.02470448,
           0.00669921, -0.02944209],
         ...,
         [ 0.05093836,  0.00481187, -0.06391015, ...,  0.06902384,
           0.04243487, -0.03489685],
         [-0.0237824 ,  0.11210787,  0.0272832 , ...,  0.02223984,
          -0.01471804, -0.03683778],
         [-0.05005392,  0.13563147,  0.09409818, ..., -0.03858449,
          -0.06823083, -0.01196058]],
 
        [[-0.02736387,  0.0049599 ,  0.0105835 , ..., -0.03036787,
          -0.02301507,  0.01367296],
         [ 0.03552669,  0.02423947, -0.04462584, ...,  0.05577949,
           0.03034067, -0.04285526],
         [ 0.07137013, -0.02768523, -0.1358293 , ...,  0.07105212,
           0.0737463 , -0.046

In [18]:
# If we connect them we get one layer forward and one backward - we can do it easy with Bidirectional
lstm_f = LSTM(64, return_sequences = True, return_state = True, go_backwards = False)
lstm_b = LSTM(64, return_sequences = True, return_state = True, go_backwards = True)

In [19]:
# We can't use it for forecasting
bidirectional = Bidirectional(LSTM(64))

In [20]:
bidirectional(x)

<tf.Tensor: shape=(53, 128), dtype=float32, numpy=
array([[ 0.09598389,  0.01543401, -0.08028837, ...,  0.05224259,
        -0.00683834,  0.00316234],
       [ 0.00353444,  0.02155106,  0.04862105, ..., -0.03808236,
        -0.03166176,  0.04371594],
       [-0.03793007, -0.02654384,  0.07642446, ..., -0.10433687,
        -0.0113714 ,  0.03589742],
       ...,
       [-0.01711016,  0.0319676 , -0.08917905, ...,  0.03776072,
         0.03939596, -0.01436477],
       [ 0.01959075, -0.01092621,  0.00166894, ...,  0.11434265,
        -0.01175871, -0.07473484],
       [ 0.02214548, -0.02542269,  0.01146825, ..., -0.00290614,
        -0.01312077,  0.01734997]], dtype=float32)>

In [21]:
lstm_with_embedding = Sequential([
    Embedding(10000, 400), 
    LSTM(64)
])

In [22]:
lstm_with_embedding.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 400)         4000000   
_________________________________________________________________
lstm_4 (LSTM)                (None, 64)                119040    
Total params: 4,119,040
Trainable params: 4,119,040
Non-trainable params: 0
_________________________________________________________________


In [23]:
tf.keras.preprocessing.text.Tokenizer()