In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

<h1>Introduction To Deep Learning - Basic Models</h1>

In [3]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
# (2a + 3b) ** 2

def compute(a, b): 
    return tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

In [5]:
a = tf.constant(5)
b = tf.constant(10)

In [6]:
compute(5, 10)

<tf.Tensor: shape=(), dtype=int32, numpy=1600>

In [7]:
type(compute(a, b))

tensorflow.python.framework.ops.EagerTensor

In [8]:
compute(a, b).numpy()

1600

In [9]:
type(compute(a, b).numpy())

numpy.int32

In [10]:
compute([1, 2, 3, 5], [4, 5, 6, 10])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [11]:
compute(np.array([1, 2, 3, 5]), np.array([4, 5, 6, 10]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [12]:
compute(5, 10)

<tf.Tensor: shape=(), dtype=int32, numpy=1600>

In [13]:
# This is clear python - nothing similar with TF or numpy.
def compute(a, b): 
    return (2 * a + 3 * b) ** 2

In [14]:
compute(2, 3)

169

In [15]:
type(compute(2, 3))

int

In [16]:
# This will give an error - in python list there are no method compute.
compute([1, 2, 3, 5], [4, 5, 6, 10])

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [17]:
# Very big differenece between functions with TF and without it.
compute(np.array([1, 2, 3, 5]), np.array([4, 5, 6, 10]))

array([ 196,  361,  576, 1600], dtype=int32)

In [18]:
@tf.function # Annotation - not works with lists, but works with np.array.
def compute(a, b): 
    return (2 * a + 3 * b) ** 2

In [19]:
# Different reslt, compared with pure python function.
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [20]:
compute(np.array([1, 2, 3, 5]), np.array([4, 5, 6, 10]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [21]:
writer = tf.summary.create_file_writer("logs")

a, b = tf.constant([2, 3, 4]), tf.constant([3, 4, 5])
tf.summary.trace_on(graph = True, profiler = True)
result = compute(a, b)
print(result.numpy())
with writer.as_default():
    tf.summary.trace_export(name = "compute_trace", step = 0, profiler_outdir = "logs")

Instructions for updating:
use `tf.profiler.experimental.start` instead.
[169 324 529]
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
Instructions for updating:
`tf.python.eager.profiler` has deprecated, use `tf.profiler` instead.
